config/routes.rb
Rails.application.routes.draw do

  localized do

    root 'home#index'

    devise_for :users, controllers: { registrations: 'registrations' }

    resource :contact
    resource :team
    resource :media

    resources :groups do
      post :order, on: :collection
    end
    resources :coaches
    resources :news_posts
    resources :fighters
    resources :trainings

    resources :passes
    resources :videos, only: [:index, :new, :create, :destroy]
    resources :slides
    resources :comments, only: [:new, :create, :destroy]
    resources :events
    resources :messages do
      post :read, on: :member
    end
    resources :faqs
    resources :members do
      resources :payments
    end
    resources :meetings
    resources :personal_trainings, only: :index
    resources :users do
      resources :meetings, only: :index, controller: 'users/meetings' do
        post :sign_up, on: :member
        delete :cancel, on: :member
      end
    end

    resources :partners, only: [:new, :create, :destroy] do
      post :order, on: :collection
    end
    resources :galleries do
      post :order, on: :collection
    end

    resources :pages, only: [:index, :new, :edit, :create] do
      post :order, on: :collection
      resources :page_contents, except: :show do
        post :order, on: :collection
      end
    end

    root "home#index"

    put "/:id", to: "pages#update"
    patch "/:id", to: "pages#update"
    delete "/:id", to: "pages#destroy"
    get "/:id", to: "pages#show", constraints: { id: /(?!.*(en|ru)).*/ }, as: :page
  
  end
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  
  scope :ordered, -> { order("question ASC") }
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  
  before_action :set_faq, only: [:edit, :update, :destroy]
  page "faqs"
  
  def index
    @faqs = Faq.ordered
  end
  
  def new
    @faq = Faq.new
    authorize(@faq)
  end
  
  def create
    @faq = Faq.new(faq_params)
    authorize(@faq)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to friendly_page_url(@page), notice: "Pytanie zostało dodane" }
      else
        format.html { render action: "new" }
      end
    end
  end
  
  def edit
  end
  
  def update
    respond_to do |format|
      if @faq.update_attributes(faq_params)
        format.html { redirect_to friendly_page_url(@page), notice: "Pytanie zostało zaktualizowane" }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @faq.destroy
    
    respond_to do |format|
      format.html { redirect_to friendly_page_url(@page), notice: "Pytanie zostało usunięte" }
      format.json { head :ok }
    end
  end
  
  private
  
  def set_faq
    @faq = Faq.find(params[:id])
    authorize(@faq)
  end
  
  def faq_params
    params.require(:faq).permit(:question, :answer)
  end
  
  
end

app/views/faqs/_form.html.haml
= simple_form_for @faq do |f|
  .form-inputs
    = f.input :question
    = f.input :answer, as: :wysihtml5
  .form-actions
    = f.button :submit

app/views/faqs/edit.html.haml
%h1.form Edytowanie pytania
= render "form"

app/views/faqs/index.html.haml
= admin_menu(inline: true) do
  = admin_link_to "new", "Dodaj pytanie", new_faq_path, method: :get if can? :create, Faq
  = admin_link_to "edit", "Edytuj stronę", edit_page_path(@page), method: :get if can? :edit, Page
  = admin_link_to "delete", "Usuń stronę", page_path(@page), data: { confirm: "Na pewno chcesz usunąć tę stronę?" }, method: :delete if can? :destroy, Page

%ol.questions-list
  - @faqs.map(&:question).each_with_index do |question, index|
    %li.question-item{ id: "question-#{index+1}" }= link_to question, faqs_path(id: index+1)


%ul.faqs-list
  - @faqs.each_with_index do |faq, index|
    %li.faq-item{ id: "faq-#{index+1}" }
      .faq-question= faq.question
      .faq-answer= faq.answer.html_safe
      = admin_menu do
        = admin_link_to "edit", "Edytuj pytanie", edit_faq_path(faq), method: :get if can? :edit, Faq
        = admin_link_to "delete", "Usuń pytanie", faq_path(faq), data: { confirm: "Czy na pewno chcesz usunąć to pytanie?" }, method: :delete if can? :destroy, Faq
.clearfix

app/views/faqs/new.html.haml
%h1.form Dodawanie pytania
= render "form"