config/routes.rb
Rails.application.routes.draw do

  localized do

    root 'home#index'

    devise_for :users, controllers: { registrations: 'registrations' }

    resource :contact
    resource :team
    resource :media

    resources :groups do
      post :order, on: :collection
    end
    resources :coaches
    resources :news_posts
    resources :fighters
    resources :trainings

    resources :passes
    resources :videos, only: [:index, :new, :create, :destroy]
    resources :slides
    resources :comments, only: [:new, :create, :destroy]
    resources :events
    resources :messages do
      post :read, on: :member
    end
    resources :faqs
    resources :members do
      resources :payments
    end
    resources :meetings
    resources :personal_trainings, only: :index
    resources :users do
      resources :meetings, only: :index, controller: 'users/meetings' do
        post :sign_up, on: :member
        delete :cancel, on: :member
      end
    end

    resources :partners, only: [:new, :create, :destroy] do
      post :order, on: :collection
    end
    resources :galleries do
      post :order, on: :collection
    end

    resources :pages, only: [:index, :new, :edit, :create] do
      post :order, on: :collection
      resources :page_contents, except: :show do
        post :order, on: :collection
      end
    end

    root "home#index"

    put "/:id", to: "pages#update"
    patch "/:id", to: "pages#update"
    delete "/:id", to: "pages#destroy"
    get "/:id", to: "pages#show", constraints: { id: /(?!.*(en|ru)).*/ }, as: :page
  
  end
end

app/models/news_post.rb
class NewsPost < ActiveRecord::Base
  
  has_many :comments, dependent: :destroy
  
  mount_uploader :image, NewsImageUploader
  
  scope :ordered, -> { order("created_at DESC") }
  
end

app/controllers/news_posts_controller.rb
class NewsPostsController < ApplicationController
  
  before_action :set_news_post, only: [:edit, :update, :destroy, :show]
  page "news_posts"
  
  def index
    @news_posts = PaginatingDecorator.decorate(NewsPost.ordered.page(params[:page]).per(10), with: NewsPostsDecorator)
    @comment = Comment.new
    @events = Event.future.ordered.limit(4).decorate
  end
  
  def show
  end
  
  def new
    @news_post = NewsPost.new
  end
  
  def edit
  end
  
  def create
    @news_post = NewsPost.create(news_post_params)
    respond_to do |format|
      if @news_post.save
        format.html { redirect_to news_posts_path, notice: "Aktualność została dodana" }
      else
        format.html { render action: "new" }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @news_post.update_attributes(news_post_params)
        format.html { redirect_to friendly_page_url(@page), notice: "Aktualność zostało zaktualizowana" }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @news_post.destroy
    
    respond_to do |format|
      format.html { redirect_to friendly_page_url(@page), notice: "Aktualność została usunięta" }
      format.json { head :ok }
    end
  end
  
  private
  
  def news_post_params
    params.require(:news_post).permit(:title, :content, :image)
  end
  
  def set_news_post
    @news_post = NewsPost.find(params[:id])
  end
  
end

app/views/news_posts/_comments.html.haml
.comments-wrapper{ data: { role: "comments-wrapper" } }
  %section.comments{ data: { role: "comments" } }
    .show-comments-link-wrapper
      = link_to t(".show_comments", count: news.comments.count), "#", class: "show-comments-link", data: { role: "show-comments-link" }
    %ul.comments-list
      - news.comments.ordered.each do |comment|
        %li.comment-item
          .comment-author-wrapper
            %span.comment-text= t(".added")
            %span= short_date(comment.created_at)
            %span.comment-text= t(".by")
            %span.comment-author= comment.author
          .comment-content
            = comment.content
          = admin_menu do
            = admin_link_to "delete", "Usuń komentarz", comment_path(comment), method: :delete, data: { confirm: "Jesteś pewien, że chcesz usunąć ten komentarz?" } if can? :destroy, Comment

    %section.add-comment
      %h2= t(".add_comment")
      = simple_form_for @comment do |f|
        = f.input :content
        .two-inputs
          = f.input :author
          = f.input :humanizer_answer, label: @comment.humanizer_question
        = f.input :humanizer_question_id, as: :hidden
        = f.input :news_post_id, as: :hidden, input_html: { value: news.id }
        = f.button :submit

app/views/news_posts/_events.html.haml
%h2= t(".closest_events")
%ul.news-posts-events
  - @events.each do |event|
    %li.news-post-event-item
      = link_to event_path(event) do
        .date= event.date
        .event-content
          = event.short_title
          = event.city
        .clearfix
      %nav.event
        %i.icon.small-grey-right-arrow
        %i.icon.small-yellow-right-arrow
      = admin_menu do
        = admin_link_to "edit", "Edytuj wydarzenie", edit_event_path(event) if can? :edit, Event
        = admin_link_to "delete", "Usuń wydarzenie", event_path(event), method: :delete, data: { confirm: "Jesteś pewien, że chcesz usunąć to wydarzenie?" } if can? :destroy, Event
        
%footer.news-posts-events-footer
  = link_to events_path, class: "more" do
    %span Wszystkie wydarzenia
    %i.icon.small-yellow-right-arrow
    %i.icon.small-grey-right-arrow
  

app/views/news_posts/_form.html.haml
= simple_form_for @news_post do |f|
  .form-inputs
    = f.input :title
    = f.input :image, as: :file
    = f.input :content, as: :wysihtml5
  .form-actions
    = f.button :submit
    
    

app/views/news_posts/edit.html.haml
%h1.form Edytowanie aktualności
= render "form"

app/views/news_posts/index.html.haml
= admin_menu(inline: true) do
  = admin_link_to "new", "Dodaj aktualność", new_news_post_path if can? :create, NewsPost
  = admin_link_to "new", "Dodaj wydarzenie", new_event_path if can? :create, Event
  = admin_link_to "edit", "Edytuj stronę", edit_page_path(@page), method: :get if can? :edit, Page
  = admin_link_to "delete", "Usuń stronę", page_path(@page), data: { confirm: "Na pewno chcesz usunąć tę stronę?" }, method: :delete if can? :destroy, Page

%section.news-posts
  .left-column
    %ul.news-posts-list
      - @news_posts.each do |news|
        %li.news-post-item
          .news-post-header
            .news-post-calender
              .news-post-day= news.day
              .news-post-month= news.month
            %h1.news-post-title= news.title
            .clearfix
          .clearfix
          .news-post-content= news.content
          = news.image
          = admin_menu do
            = admin_link_to "edit", "Edytuj aktualność", edit_news_post_path(news) if can? :edit, NewsPost
            = admin_link_to "delete", "Usuń aktualność", news_post_path(news), method: :delete, data: { confirm: "Jesteś pewien, że chcesz usunąć tę aktualność?" } if can? :destroy, NewsPost
        
          =# render "comments", news: news
                
    = paginate @news_posts
          
        
        
  .right-column
    = render "events"

  .clearfix

app/views/news_posts/new.html.haml
%h1.form Dodawanie aktualności
= render "form"