config/routes.rb
Rails.application.routes.draw do

  localized do

    root 'home#index'

    devise_for :users, controllers: { registrations: 'registrations' }

    resource :contact
    resource :team
    resource :media

    resources :groups do
      post :order, on: :collection
    end
    resources :coaches
    resources :news_posts
    resources :fighters
    resources :trainings

    resources :passes
    resources :videos, only: [:index, :new, :create, :destroy]
    resources :slides
    resources :comments, only: [:new, :create, :destroy]
    resources :events
    resources :messages do
      post :read, on: :member
    end
    resources :faqs
    resources :members do
      resources :payments
    end
    resources :meetings
    resources :personal_trainings, only: :index
    resources :users do
      resources :meetings, only: :index, controller: 'users/meetings' do
        post :sign_up, on: :member
        delete :cancel, on: :member
      end
    end

    resources :partners, only: [:new, :create, :destroy] do
      post :order, on: :collection
    end
    resources :galleries do
      post :order, on: :collection
    end

    resources :pages, only: [:index, :new, :edit, :create] do
      post :order, on: :collection
      resources :page_contents, except: :show do
        post :order, on: :collection
      end
    end

    root "home#index"

    put "/:id", to: "pages#update"
    patch "/:id", to: "pages#update"
    delete "/:id", to: "pages#destroy"
    get "/:id", to: "pages#show", constraints: { id: /(?!.*(en|ru)).*/ }, as: :page
  
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :trainings, class_name: "TrainingDay", dependent: :destroy
  has_many :meetings, through: :trainings

  before_create :set_default_position

  accepts_nested_attributes_for :trainings, allow_destroy: true
  LEVELS = %w(beginner advanced middle mixed youth)

  scope :ordered, -> { order("position ASC") }

  private

  def set_default_position
    self.position ||= 1 + (self.class.maximum(:position) || 0)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  before_action :set_group, only: [:edit, :update, :destroy]
  page "groups"
  def index
    @groups = Group.ordered
    @groups = GroupDecorator.decorate_collection(@groups)
  end
  
  def new
    @group = Group.new
    authorize(@group)
  end
  
  def create
    @group = Group.new(group_params)
    authorize(@group)
    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: "Grupa została dodana" }
      else
        format.html { render action: "new" }
      end
    end
  end
  
  def edit
  end
  
  def show
  end
  
  def update
    respond_to do |format|
      if @group.update_attributes(group_params)
        format.html { redirect_to friendly_page_url(@page), notice: "Grupa została zaktualizowana." }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @group.destroy
    
    respond_to do |format|
      format.html { redirect_to friendly_page_path(@page), notice: "Grupa została usunięta" }
      format.json { head :ok }
    end
  end
  
  def order
    params[:group].each_with_index do |id, index|
      Group.where(id: id).update_all(position: index)
    end
    flash.now[:notice] = "Kolejność grup została zapisana."
    render nothing: true
  end
  
  private
  
  def set_group
    @group = Group.find(params[:id])
    authorize(@group)
  end
  
  def group_params
    params.require(:group).permit(:name, :number, :level, trainings_attributes: [:group_id, :name, :id, :_destroy, :time_start, :time_end])
  end
  
end

app/views/groups/_form.html.haml
= simple_form_for @group do |f|
  .form-inputs
    .three-inputs
      = f.input :name
      = f.input :number
      = f.input :level, collection: group_levels_collection_for_select, input_html: { value: @group.level }
    
    %div{ data: { component: "nested-form-objects" } }
      = link_to "Dodaj dzień", "#", data: { role: "add-object" }

      %div{ data: { role: "objects-container" } }
        - f.object.trainings.each_with_index do |training, index|
          = render "trainings/fields", f: f, training: training, index: index

      %script{ type: "text/html", data: { role: "template" } }
        = render "trainings/fields", f: f, training: TrainingDay.new, index: "{{index}}"
    
  .form-actions
    = f.button :submit

app/views/groups/edit.html.haml
%h1.form Edytowanie grupy
= render "form"

app/views/groups/index.html.haml
%div{ data: { role: "sortable", :"update-url" => order_groups_path } }
  = admin_menu(inline: true) do
    = admin_link_to "edit", "Edytuj stronę", edit_page_path(@page), method: :get if can? :edit, Page
    = admin_link_to "new", "Dodaj grupę", new_group_path if can? :create, Group
    = admin_link_to "delete", "Usuń stronę", page_path(@page), data: { confirm: "Na pewno chcesz usunąć tę stronę?" }, method: :delete if can? :destroy, Page
    = admin_link_to "sort_horizontal", "Zmień kolejność", "#", data: { action: "toggle-sort" } if can? :sort_order, Group
    = admin_link_to "create_week_meetings", "Otwórz zapisy na kolejny tydzień", new_meeting_path if can? :create, Meeting

  - if Meeting.active.count > 1
    %p.meetings-date-range
      %span Otwarte zapisy od
      %span= format_meeting_date(Meeting.first_active_date)
      %span do
      %span= format_meeting_date(Meeting.last_active_date)
  %table.schedule
    %thead
      %tr
        %th
        %th= t(".monday")
        %th= t(".tuesday")
        %th= t(".wednesday")
        %th= t(".thursday")
        %th= t(".friday")
    %tbody{ data: { role: "sortable-list" } }
      - @groups.each do |group|
        %tr.sortable-item{ id: group.sortable_id }
          %td.group{ class: group.level }
            = group.name
            %span.group-number= group.number
            = admin_menu do
              = admin_link_to "edit", "Edytuj grupę", edit_group_path(group) if can? :edit, Group
              = admin_link_to "delete", "Usuń grupę", group_path(group), method: :delete, data: { confirm: "Czy na pewno chcesz usunąć tę grupę?" } if can? :destroy, Group
          - TrainingDay::DAY_NAMES.each do |day_name|
            - meeting = group.get_meeting(day_name).try(:decorate)
            %td.training-day
              - if meeting.present?
                = meeting.users_count(with_number: true)
                - if meeting.open? && !meeting.with_user?(current_user)
                  - if current_user.nil?
                    = link_to new_user_session_path, class: "sign-up-link" do
                      %span.sign-up= t("meeting.sign_up")
                      %span.sign-up-date= "(#{meeting.event_at_formatted})"
                  - else
                    = link_to sign_up_user_meeting_path(current_user, meeting.id), method: :post, class: "sign-up-link",
                      data: { confirm: "Czy na pewno chcesz się zapisać na zajęcia #{meeting.event_at_formatted}" } do
                      %span.sign-up= t("meeting.sign_up")
                      %span.sign-up-date= "(#{meeting.event_at_formatted})"
              = group.training_day(day_name)
              - if meeting.present? && meeting.with_user?(current_user)
                = meeting.sign_up_message(current_user)

- Group::LEVELS.each do |level|
  %p
    = t(".color")
    %span.group-color{ class: level }
    = t(".#{level}_group")

app/views/groups/new.html.haml
%h1.form Dodawanie grupy
= render "form"