config/routes.rb
Rails.application.routes.draw do

  localized do

    root 'home#index'

    devise_for :users, controllers: { registrations: 'registrations' }

    resource :contact
    resource :team
    resource :media

    resources :groups do
      post :order, on: :collection
    end
    resources :coaches
    resources :news_posts
    resources :fighters
    resources :trainings

    resources :passes
    resources :videos, only: [:index, :new, :create, :destroy]
    resources :slides
    resources :comments, only: [:new, :create, :destroy]
    resources :events
    resources :messages do
      post :read, on: :member
    end
    resources :faqs
    resources :members do
      resources :payments
    end
    resources :meetings
    resources :personal_trainings, only: :index
    resources :users do
      resources :meetings, only: :index, controller: 'users/meetings' do
        post :sign_up, on: :member
        delete :cancel, on: :member
      end
    end

    resources :partners, only: [:new, :create, :destroy] do
      post :order, on: :collection
    end
    resources :galleries do
      post :order, on: :collection
    end

    resources :pages, only: [:index, :new, :edit, :create] do
      post :order, on: :collection
      resources :page_contents, except: :show do
        post :order, on: :collection
      end
    end

    root "home#index"

    put "/:id", to: "pages#update"
    patch "/:id", to: "pages#update"
    delete "/:id", to: "pages#destroy"
    get "/:id", to: "pages#show", constraints: { id: /(?!.*(en|ru)).*/ }, as: :page
  
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  
  page "videos"
  
  def index
    @videos = Video.all
  end
  
  def new
    @video = Video.new
    authorize(@video)
  end
  
  def create
    @video = Video.create(video_params)
    authorize(@video)
    respond_to do |format|
      if @video.save
        format.html { redirect_to friendly_page_url(@page), notice: "Film został dodany" }
      else
        format.html { render action: "new" }
      end
    end
  end
  
  def destroy
    @video = Video.find(params[:id])
    authorize(@video)
    
    @video.destroy
    
    respond_to do |format|
      format.html { redirect_to friendly_page_url(@page), notice: "Film został usunięty" }
      format.json { head :ok }
    end
  end
  
  private
  
  def video_params
    params.require(:video).permit(:link)
  end
  
end

app/views/videos/index.html.haml
= admin_menu(inline: true) do 
  = admin_link_to "new", "Dodaj video", new_video_path if can? :create, Video
  = admin_link_to "edit", "Edytuj stronę", edit_page_path(@page), method: :get if can? :edit, Page
  = admin_link_to "delete", "Usuń stronę", page_path(@page), data: { confirm: "Na pewno chcesz usunąć tę stronę?" }, method: :delete if can? :destroy, Page
  
%section.video
  - @videos.each do |video|
    .video-item
      = video.link.html_safe
      = admin_menu do 
        = admin_link_to "delete", "Usuń video", video_path(video), method: :delete, data: { confirm: "Czy na pewno chcesz usunąć ten film?" } if can? :destroy, Video
  

app/views/videos/new.html.haml
= simple_form_for @video do |f|
  .form-inputs
    = f.input :link
  .form-actions
    = f.button :submit
  